---

- name: Make sure rsyslog is installed
  yum:
    name: '{{ item }}'
    state: 'latest'
  with_items: rsyslog_packages
  when: rsyslog_packages is defined and rsyslog_packages
  notify: [ 'Restart rsyslogd' ]

- name: Install bash_history_log scripts
  copy:
    src: 'etc/'
    dest: '/etc/'
    owner: 'root'
    group: 'root'
    mode: '0644'

- include: pools.yml
  when: rsyslog_manage_pools is defined and rsyslog_manage_pools == True

